FROM java:8

VOLUME [ "/var/lib/kite/log" ]

# Make port 8080 available to the world outside this container
EXPOSE 8080

# the application's jar file
ARG JAR_FILE=build/libs/kite-0.0.2.jar

# Add the applicatio 's jar to the container
ADD ${JAR_FILE} kite-boot.jar

# Run the jar file
ENTRYPOINT [ "java", "-jar","/kite-boot.jar" ]